Tidy up.

diff --git a/bin/cram b/bin/cram
--- a/bin/cram
+++ b/bin/cram
@@ -1,16 +1,29 @@
 #!/usr/bin/env bash
 
-if ! [ -x "$(command -v pigz)" ]; then
-	echo >&2 "I require pigz but it's not installed.  Aborting."
-	exit 1
-fi
+main() {
+	have_pigz=$(check_pigz)
+	if [[ "$have_pigz" == "1" ]]; then
+		printf "%s\n" "Could not find pigz, we need pigz!"
+		exit 1
+	fi
 
-if [ "$#" -eq "2" ]; then
-	dt=$(date --iso-8601)
-	threads=$(nproc --all)
-	filename="${1%.tar.gz}_${dt}.tar.gz"
-	echo "[$0] Compressing ${@:2} into ${filename}"
-	tar cf - ${@:2} | pigz -9 -p "${threads}" > "${filename}"
-else
-	echo "[$0] Usage: $0 compressed_file_name files_or_dir_to_be_compressed"
-fi
+	compress "$@"
+}
+
+compress() {
+	if [[ "$#" -eq "2" ]]; then
+		local dt=$(date --iso-8601)
+		local threads=$(nproc --all)
+		local filename="${1%.tar.gz}_${dt}.tar.gz"
+		echo "[$0] Compressing ${@:2} into ${filename}"
+		tar cf - ${@:2} | pigz -9 -p "${threads}" > "${filename}"
+	else
+		echo "[$0] Usage: $0 compressed_file_name files_or_dir_to_be_compressed"
+	fi
+}
+
+check_pigz() {
+	command -v pigz >/dev/null 2>&1 || echo 1
+}
+
+main "$@"
